# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET API

on:
  workflow_run:
    workflows: [".NET"]
    branches: [ "main" ]
    types:
      - completed
  push:
    branches: [ "main" ]
    paths:
      - 'WebApi/**'
      - '.github/workflows/dotnetAPI.yml'

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: "webapi-$(github.run_id)"
  AZURE_WEBAPP_PACKAGE_PATH: './WebApi/release'

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: WebApi
            
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish package
      run: dotnet publish -o ./release /p:WebPublishMethod=Package -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: webapi/release/**
        
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: drop   
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: logout
      run: |
        az logout